# Generated by Django 5.0.7 on 2024-10-04 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان لینک')),
                ('link', models.URLField(verbose_name='آدرس لینک')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_link_set', to='Blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'لینک مفید',
                'verbose_name_plural': 'لینک های مفید',
            },
        ),
    ]
