# Generated by Django 5.0.7 on 2024-10-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('id',), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
