# Generated by Django 5.0.7 on 2024-08-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, verbose_name='عنوان در url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'دسته بندی فایل ',
                'verbose_name_plural': 'دسته بندی ها فایل ها',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='عنوان ملک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس')),
                ('price', models.CharField(max_length=128, verbose_name='قیمت')),
                ('description', models.CharField(max_length=512, verbose_name='توضیحات')),
                ('address', models.CharField(max_length=256, verbose_name='آدرس')),
                ('area', models.CharField(blank=True, max_length=48, null=True, verbose_name='متراژ')),
                ('room', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد خواب ')),
                ('bath', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد سرویس ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'فایل ',
                'verbose_name_plural': 'فایل ها',
            },
        ),
    ]
