# Generated by Django 5.0.7 on 2024-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_estate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_title',
            field=models.CharField(default=1, max_length=48, verbose_name='عنوان انگلیسی'),
            preserve_default=False,
        ),
    ]
