# Generated by Django 5.0.7 on 2024-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_category_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_slug',
            field=models.CharField(blank=True, editable=False, max_length=48, null=True, verbose_name='عنوان انگلیسی'),
        ),
    ]
