# Generated by Django 5.0.7 on 2024-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_category_url_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'دسته بندی فایل ', 'verbose_name_plural': 'دسته بندی ها فایل ها'},
        ),
        migrations.AddField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
