# Generated by Django 5.0.7 on 2024-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('is_main', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='آدرس')),
                ('work_time', models.CharField(max_length=128, verbose_name='تایم کاری')),
                ('instagram', models.CharField(max_length=48, verbose_name='اینستاگرام')),
                ('phone', models.CharField(max_length=19, verbose_name='شماره ')),
                ('location', models.URLField(max_length=2048, verbose_name='لوکیشن گوگل مپ')),
                ('is_main', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دسترسی به ما',
                'verbose_name_plural': 'دسترسی به ما',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_logo', models.ImageField(upload_to='logo/', verbose_name='عکس')),
                ('is_main', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'نام سایت',
                'verbose_name_plural': 'نام سایت',
            },
        ),
    ]
