# Generated by Django 5.0.7 on 2024-08-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='location',
        ),
    ]
