# Generated by Django 5.0.7 on 2024-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_footer_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='نام')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره')),
                ('text', models.TextField(verbose_name='شماره')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی',
            },
        ),
    ]
